//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChiDaram.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChiDaram.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح دسترسی.
        /// </summary>
        public static string AccessLevel {
            get {
                return ResourceManager.GetString("AccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل پیوست.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نویسنده.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز فعلی.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما مجاز به انجام این عملیات نیستید.
        /// </summary>
        public static string ErrorMessageAccessIsDenied {
            get {
                return ResourceManager.GetString("ErrorMessageAccessIsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم انتخاب شده در سیستم استفاده شده است و قابل حذف نمی باشد.
        /// </summary>
        public static string ErrorMessageCanNotDelete {
            get {
                return ResourceManager.GetString("ErrorMessageCanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; وارد شده قبلا گرفته شده است.
        /// </summary>
        public static string ErrorMessageDuplicateExistStringFormat {
            get {
                return ResourceManager.GetString("ErrorMessageDuplicateExistStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; غیر فعال است.
        /// </summary>
        public static string ErrorMessageIsDeactive {
            get {
                return ResourceManager.GetString("ErrorMessageIsDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; را اشتباه وارد کرده اید.
        /// </summary>
        public static string ErrorMessageNotCorrectStringFormat {
            get {
                return ResourceManager.GetString("ErrorMessageNotCorrectStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات &quot;{0}&quot; در دیتابیس موجود نیست.
        /// </summary>
        public static string ErrorMessageNotExistInDataBaseStringFormat {
            get {
                return ResourceManager.GetString("ErrorMessageNotExistInDataBaseStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت زمان مجاز برای فعال سازی رمز یکبار مصرف تمام شده است، لطفا دوباره سعی کنید.
        /// </summary>
        public static string ErrorMessageOtpPasswordEnableTimeExpired {
            get {
                return ResourceManager.GetString("ErrorMessageOtpPasswordEnableTimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور یکبار مصرف را اشتباه وارد کرده اید.
        /// </summary>
        public static string ErrorMessageOtpPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("ErrorMessageOtpPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور و تکرار آن باید با یکدیگر یکسان باشند.
        /// </summary>
        public static string ErrorMessagePasswordCompareValidation {
            get {
                return ResourceManager.GetString("ErrorMessagePasswordCompareValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; باید بین &quot;{1}&quot; و &quot;{2}&quot; باشد.
        /// </summary>
        public static string ErrorMessageRangeValidationStringFormat {
            get {
                return ResourceManager.GetString("ErrorMessageRangeValidationStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای امنیتی ReCaptcha رخ داده است.
        /// </summary>
        public static string ErrorMessageRecaptchaIsWrong {
            get {
                return ResourceManager.GetString("ErrorMessageRecaptchaIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; معتبر وارد نمایید.
        /// </summary>
        public static string ErrorMessageRequiredCorrectValueStringFormat {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredCorrectValueStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; را وارد نکرده اید.
        /// </summary>
        public static string ErrorMessageRequiredValidationStringFormat {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredValidationStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; باید حداقل &quot;{2}&quot; و حداکثر &quot;{1}&quot; کاراکتر باشد.
        /// </summary>
        public static string ErrorMessageStringLengthValidationStringFormat {
            get {
                return ResourceManager.GetString("ErrorMessageStringLengthValidationStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تگ های {0} به درستی بسته نشده اند.
        /// </summary>
        public static string ErrorMessageTagsNotCloseStringFormat {
            get {
                return ResourceManager.GetString("ErrorMessageTagsNotCloseStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسوند فایل &quot;{0}&quot; پشتیبانی نمی شود.
        /// </summary>
        public static string ErrorMessageUploadedFileExtensionNotSupport {
            get {
                return ResourceManager.GetString("ErrorMessageUploadedFileExtensionNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم فایل آپلود شده باید کمتر از &quot;{0}&quot; باشد.
        /// </summary>
        public static string ErrorMessageUploadedFileLength {
            get {
                return ResourceManager.GetString("ErrorMessageUploadedFileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل آپلود شده باید دارای پسوند باشد.
        /// </summary>
        public static string ErrorMessageUploadedFileMustHaveAnExtension {
            get {
                return ResourceManager.GetString("ErrorMessageUploadedFileMustHaveAnExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فایل آپلود شده باید کمتر از &quot;{0}&quot; کاراکتر باشد.
        /// </summary>
        public static string ErrorMessageUploadedFileNameIsNotValid {
            get {
                return ResourceManager.GetString("ErrorMessageUploadedFileNameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل آپلود شده یافت نشد، لطفا دوباره فایل را بارگذاری نمائید.
        /// </summary>
        public static string ErrorMessageUploadedFileNotFound {
            get {
                return ResourceManager.GetString("ErrorMessageUploadedFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور اشتباه است.
        /// </summary>
        public static string ErrorMessageUsernameOrPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("ErrorMessageUsernameOrPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما نمی توانید {0} خودتان را حذف یا غیر فعال کنید.
        /// </summary>
        public static string ErrorMessageYouCanNotDeleteOrDisableYourself {
            get {
                return ResourceManager.GetString("ErrorMessageYouCanNotDeleteOrDisableYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیلو بایت.
        /// </summary>
        public static string KiloByte {
            get {
                return ResourceManager.GetString("KiloByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اصلی.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مگابایت.
        /// </summary>
        public static string MegaByte {
            get {
                return ResourceManager.GetString("MegaByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد منو.
        /// </summary>
        public static string MenuCode {
            get {
                return ResourceManager.GetString("MenuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد منوها.
        /// </summary>
        public static string MenuCodes {
            get {
                return ResourceManager.GetString("MenuCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز جدید.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۰.
        /// </summary>
        public static string Number0 {
            get {
                return ResourceManager.GetString("Number0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفر.
        /// </summary>
        public static string Number0String {
            get {
                return ResourceManager.GetString("Number0String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۱.
        /// </summary>
        public static string Number1 {
            get {
                return ResourceManager.GetString("Number1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره.
        /// </summary>
        public static string Number10 {
            get {
                return ResourceManager.GetString("Number10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک.
        /// </summary>
        public static string Number1String {
            get {
                return ResourceManager.GetString("Number1String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۲.
        /// </summary>
        public static string Number2 {
            get {
                return ResourceManager.GetString("Number2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دو.
        /// </summary>
        public static string Number2String {
            get {
                return ResourceManager.GetString("Number2String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۳.
        /// </summary>
        public static string Number3 {
            get {
                return ResourceManager.GetString("Number3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه.
        /// </summary>
        public static string Number3String {
            get {
                return ResourceManager.GetString("Number3String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۴.
        /// </summary>
        public static string Number4 {
            get {
                return ResourceManager.GetString("Number4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهار.
        /// </summary>
        public static string Number4String {
            get {
                return ResourceManager.GetString("Number4String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۵.
        /// </summary>
        public static string Number5 {
            get {
                return ResourceManager.GetString("Number5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنج.
        /// </summary>
        public static string Number5String {
            get {
                return ResourceManager.GetString("Number5String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۶.
        /// </summary>
        public static string Number6 {
            get {
                return ResourceManager.GetString("Number6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شش.
        /// </summary>
        public static string Number6String {
            get {
                return ResourceManager.GetString("Number6String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۷.
        /// </summary>
        public static string Number7 {
            get {
                return ResourceManager.GetString("Number7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفت.
        /// </summary>
        public static string Number7String {
            get {
                return ResourceManager.GetString("Number7String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۸.
        /// </summary>
        public static string Number8 {
            get {
                return ResourceManager.GetString("Number8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشت.
        /// </summary>
        public static string Number8String {
            get {
                return ResourceManager.GetString("Number8String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۹.
        /// </summary>
        public static string Number9 {
            get {
                return ResourceManager.GetString("Number9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نه.
        /// </summary>
        public static string Number9String {
            get {
                return ResourceManager.GetString("Number9String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اپراتور.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد مرتب سازی.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز یکبار مصرف.
        /// </summary>
        public static string OtpPassword {
            get {
                return ResourceManager.GetString("OtpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گیرندگان.
        /// </summary>
        public static string Receivers {
            get {
                return ResourceManager.GetString("Receivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        public static string RegisterDateTime {
            get {
                return ResourceManager.GetString("RegisterDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه نقش.
        /// </summary>
        public static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس امنیتی.
        /// </summary>
        public static string SecurityImage {
            get {
                return ResourceManager.GetString("SecurityImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل فرستنده.
        /// </summary>
        public static string SenderEmail {
            get {
                return ResourceManager.GetString("SenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان فرستنده.
        /// </summary>
        public static string SenderTitle {
            get {
                return ResourceManager.GetString("SenderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرتب سازی.
        /// </summary>
        public static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برچسب.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برچسب ها.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
